[package]
name = "ch_5_struct"
version = "0.1.0"
authors = ["siraj454 <64827860+Siraj454@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
