[package]
name = "error_handling"
version = "0.1.0"
authors = ["MuhammadSirajAbbasi <64827860+Siraj454@users.noreply.github.com>"]
edition = "2018"
[profile.dev]
panic="abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
